name: continuous delivery

on: [ push ]

jobs:


  # php-http
  ####################
  update-php-http:
    name: dump-components/php-http
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate dependencies
        uses: php-actions/composer@master
        with:
          command: validate
          working_dir: 'src/Dump/Http'

      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'dump-components/php-http'
          path: 'src/Dump/Http'
          deploy_key: '${{ secrets.PHP_HTTP }}'
          force: true

  # php-patterns
  ####################
  update-php-patterns:
    name: dump-components/php-patterns
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate dependencies
        uses: php-actions/composer@master
        with:
          command: validate
          working_dir: 'src/Dump/Patterns'

      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'dump-components/php-patterns'
          path: 'src/Dump/Patterns'
          deploy_key: '${{ secrets.PHP_PATTERNS }}'
          force: true

  # php-patterns
  ####################
  update-php-regex:
    name: dump-components/php-regex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate dependencies
        uses: php-actions/composer@master
        with:
          command: validate
          working_dir: 'src/Dump/Regex'

      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'dump-components/php-regex'
          path: 'src/Dump/Regex'
          deploy_key: '${{ secrets.PHP_REGEX }}'
          force: true