on:
  push:
     branches:
       - main

name: ⏫ Copy content to REBEL

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Copy the 'post' folder
    - name: Push posts
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PHP_FRAMEWORK }}
      with:
        source_file: 'src/Dump/Http' # Folder to copy
        destination_repo: 'dump-components/php-http' # Target repo
        destination_folder: '/' # Folder where to copy it
        user_email: 'dom.makowski@gmail.com'
        user_name: 'DominiqueMakowski'
        commit_message: "AUTO: Copying posts from Dom's to REBEL's website"
        git_server: 'github.com'
