name: Push sub repositories

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to another repo
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} 
      run: |
        git status && ls -lsa
