name: Validate Composer

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          # list your packages here
          - './'
          - './src/Dump/Http'
          - './src/Dump/Patterns'

    steps:
      - uses: actions/checkout@v2

      - name: log
        run: echo "validate ${{ matrix.package }} package"

      - name: Validate dependencies
        uses: php-actions/composer@master
        with:
          command: validate
          working_dir: '${{ matrix.package }}'